global using CarProject.Data.Shared.Interfaces;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Builder;
global using CarProject.Data.Services;
global using CarProject.Data.Shared.Interfaces;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore.Internal;
